### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'internal/process/task_queues.js'

### ISSUE THREAD

**Issue by danielkbx** [ozkanonur/nestjs-enlighten#10]
When installing and enabling enlighten using the information in the readme, I get this on the console:

`(node:29011) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'internal/process/task_queues.js'
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
    at /Users/yyy/Projekte/xxx/backend/node_modules/nestjs-enlighten/src/Services/Resolver/stack-resolver.ts:18:20
    at Array.map (<anonymous>)
    at StackResolverService.getProperErrorStack (/Users/yyy/Projekte/xxx/backend/node_modules/nestjs-enlighten/src/Services/Resolver/stack-resolver.ts:16:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ViewCompilerService.getCompiledView (/Users/yyy/Projekte/xxx/backend/node_modules/nestjs-enlighten/src/Services/ViewCompiler/view-compiler.service.ts:23:36)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:29011) Error: ENOENT: no such file or directory, open 'internal/process/task_queues.js'
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
    at /Users/yyy/Projekte/xxx/backend/node_modules/nestjs-enlighten/src/Services/Resolver/stack-resolver.ts:18:20
    at Array.map (<anonymous>)
    at StackResolverService.getProperErrorStack (/Users/yyy/Projekte/xxx/backend/node_modules/nestjs-enlighten/src/Services/Resolver/stack-resolver.ts:16:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ViewCompilerService.getCompiledView (/Users/yyy/Projekte/xxx/backend/node_modules/nestjs-enlighten/src/Services/ViewCompiler/view-compiler.service.ts:23:36)
(node:29011) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:180:11)
    at processPromiseRejections (internal/process/promises.js:249:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:29011) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received null
    at Object.openSync (fs.js:457:10)
    at Object.readFileSync (fs.js:368:35)
    at /Users/yyy/Projekte/xxx/backend/node_modules/nestjs-enlighten/src/Services/Resolver/stack-resolver.ts:18:20
    at Array.map (<anonymous>)
    at StackResolverService.getProperErrorStack (/Users/yyy/Projekte/xxx/backend/node_modules/nestjs-enlighten/src/Services/Resolver/stack-resolver.ts:16:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ViewCompilerService.getCompiledView (/Users/yyy/Projekte/xxx/backend/node_modules/nestjs-enlighten/src/Services/ViewCompiler/view-compiler.service.ts:23:36)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:29011) TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received null
    at Object.openSync (fs.js:457:10)
    at Object.readFileSync (fs.js:368:35)
    at /Users/yyy/Projekte/xxx/backend/node_modules/nestjs-enlighten/src/Services/Resolver/stack-resolver.ts:18:20
    at Array.map (<anonymous>)
    at StackResolverService.getProperErrorStack (/Users/yyy/Projekte/xxx/backend/node_modules/nestjs-enlighten/src/Services/Resolver/stack-resolver.ts:16:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ViewCompilerService.getCompiledView (/Users/yyy/Projekte/xxx/backend/node_modules/nestjs-enlighten/src/Services/ViewCompiler/view-compiler.service.ts:23:36)
`

Besides this, it seems that the stack displayed on the error page is wrong - or not complete at least.

**Comment by onur-ozkan** [comment]
Which node and nest versions you are using ? @danielkbx

**Comment by danielkbx** [comment]
It is Node v14.5.0 and @nest/core 7.3.2, just the currently most fresh versions.

**Comment by onur-ozkan** [comment]
> It is Node v14.5.0 and @nest/core 7.3.2, just the currently most fresh versions.

Alright, I will be working on it this weekend.

**Comment by onur-ozkan** [comment]
@danielkbx I have tried the package with Node v14.9.0 and Nest v7.4.4 and I see no errors. There were some issues on nestjs-enlighten v0.0.5-beta but it is definitely not about the errors that you mentioned above.

**Comment by onur-ozkan** [comment]
Closed due to inactivity.
