### ISSUE TITLE
'statusCode' is undefined in Services/Errors/error.service.js

### ISSUE THREAD

**Issue by Yokutto** [ozkanonur/nestjs-enlighten#7]
Hi,

I recently installed enlighten in my API and everything stopped working when an error occurs. I was wondering that something could be wrong with my API, so I installed enlighten on a newly created NestJS API and the results were the same. I couldn't fix this problem myself, so I'm here asking for your help, I'll leave the problem stack below

```
(node:5252) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'statusCode' of undefined
    at ErrorService.errorDeterminator (/home/mokyunnetwork/Gitlab/nestjs-api/node_modules/nestjs-enlighten/dist/Services/Errors/error.service.js:10:55)
    at ViewCompilerService.getCompiledView (/home/mokyunnetwork/Gitlab/nestjs-api/node_modules/nestjs-enlighten/dist/Services/ViewCompiler/view-compiler.service.js:16:78)
    at ExceptionFilter.catch (/home/mokyunnetwork/Gitlab/nestjs-api/node_modules/nestjs-enlighten/dist/Filters/exception.filter.js:31:77)
    at ExceptionsHandler.invokeCustomFilters (/home/mokyunnetwork/Gitlab/nestjs-api/node_modules/@nestjs/core/exceptions/exceptions-handler.js:33:26)
    at ExceptionsHandler.next (/home/mokyunnetwork/Gitlab/nestjs-api/node_modules/@nestjs/core/exceptions/exceptions-handler.js:13:18)
    at /home/mokyunnetwork/Gitlab/nestjs-api/node_modules/@nestjs/core/router/router-proxy.js:24:35
    at Layer.handle_error (/home/mokyunnetwork/Gitlab/nestjs-api/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/mokyunnetwork/Gitlab/nestjs-api/node_modules/express/lib/router/index.js:315:13)
    at /home/mokyunnetwork/Gitlab/nestjs-api/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/mokyunnetwork/Gitlab/nestjs-api/node_modules/express/lib/router/index.js:335:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Node version: v14.4.0
NestJS version: 7.4.1
Enlighten version: 0.0.4-beta

**Comment by onur-ozkan** [comment]
@Yokutto Thanks for your feedback, will be working on it this weekend.
